trigger: none # We only want to trigger manually or based on resources
pr: none

resources:
  pipelines:
  - pipeline: CI
    source: structurizr-dsl-plantuml-direction-updater.Build
    trigger:
      tags:
      - auto-release

variables:
- group: Publishing secrets

stages:
- stage: GithubRelease
  displayName: Github Release
  jobs:

  - job: Release
    displayName: Github Release
    pool:
      vmImage: ubuntu-latest
    steps:

    - checkout: none

    - powershell: |
        Write-Host "##vso[build.updatebuildnumber]$(resources.pipeline.CI.runName)"
        if ('$(resources.pipeline.CI.runName)'.Contains('-')) {
          Write-Host "##vso[task.setvariable variable=IsPrerelease]true"
        } else {
          Write-Host "##vso[task.setvariable variable=IsPrerelease]false"
        }
      displayName: ⚙️ Set up pipeline

    - download: CI
      artifact: packages
      displayName: 🔻 Download packages artifact
      patterns: 'packages/*'

    - download: CI
      artifact: release-dependencies
      displayName: 🔻 Download publisher artifact
      patterns: 'release-dependencies/*'

    - task: GitHubRelease@1
      displayName: 📢 Create GitHub release
      inputs:
        gitHubConnection: github_coenm_pan
        repositoryName: $(Build.Repository.Name)
        target: $(resources.pipeline.CI.sourceCommit)
        tagSource: userSpecifiedTag
        tag: v$(resources.pipeline.CI.runName)
        title: v$(resources.pipeline.CI.runName)
        isDraft: false 
        isPreRelease: $(IsPrerelease)
        assets: |
          $(Pipeline.Workspace)/CI/packages/*.nupkg
          $(Pipeline.Workspace)/CI/packages/*.snupkg
        changeLogCompareToRelease: lastNonDraftRelease
        changeLogType: issueBased
        changeLogLabels: |
          [
            { "label" : "breaking change", "displayName" : "Breaking changes", "state" : "closed" },
            { "label" : "bug", "displayName" : "Fixes", "state" : "closed" },
            { "label" : "enhancement", "displayName": "Enhancements", "state" : "closed" }
          ]
    - powershell: |
        dotnet tool install --global dotnet-releaser
        dotnet-releaser changelog --update --github-token $(GITHUB_TOKEN_NEW) $(Pipeline.Workspace)/CI/release-dependencies/dotnet-releaser.toml $(resources.pipeline.CI.runName)
      displayName: 📢 Update GitHub release using Releaser
      
- stage: nuget_org
  displayName: nuget.org
  dependsOn: GitHubRelease
  jobs:
  - deployment: push
    pool:
      vmImage: ubuntu-latest
    environment: No-Approval
    strategy:
      runOnce:
        deploy:
          steps:
          - download: CI
            artifact: packages
            displayName: Download nuget packages artifact
            patterns: 'packages/*'
          - task: NuGetToolInstaller@1
            displayName: Use NuGet 5.x
            inputs:
              versionSpec: 5.x
          - task: NuGetCommand@2
            displayName: NuGet push nupkg
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;$(Pipeline.Workspace)/**/*.snupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: nuget.org  